services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
      - ./Backend/contract.env
    depends_on:
      - redis
    volumes:
      - ./Backend:/app
      - /app/node_modules

  redis:
    image: redis:7
  
