[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Enable optimizer
optimizer = true
optimizer_runs = 200

# Set EVM version (Base supports prague)
evm_version = "prague"

# Metadata settings to avoid bytecode mismatch
[profile.default.metadata]
bytecodeHash = "none"
